"""add installments and payments

Revision ID: 2fca8a8e6646
Revises: d8f72b7ed10c
Create Date: 2026-06-03 21:52:19.891893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fca8a8e6646'
down_revision: Union[str, Sequence[str], None] = 'd8f72b7ed10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installments',
    sa.Column('enrollmentId', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('dueDate', sa.Date(), nullable=False),
    sa.Column('paidAmount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollmentId'], ['enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installments_enrollmentId'), ['enrollmentId'], unique=False)

    op.create_table('payments',
    sa.Column('enrollmentId', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paidAt', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollmentId'], ['enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_enrollmentId'), ['enrollmentId'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_enrollmentId'))

    op.drop_table('payments')
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installments_enrollmentId'))

    op.drop_table('installments')
    # ### end Alembic commands ###
