"""initial schema

Revision ID: 9524731a151b
Revises: 
Create Date: 2026-06-03 21:07:47.173765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9524731a151b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('fullName', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'teacher', 'student', name='userRole', native_enum=False), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('isActive', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('students',
    sa.Column('studentCode', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('joinedAt', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('davet', 'manuel', name='studentSource', native_enum=False), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_studentCode'), ['studentCode'], unique=True)

    op.create_table('enrollments',
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=64), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'pending', 'inactive', name='enrollmentStatus', native_enum=False), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Integer(), server_default='0', nullable=False),
    sa.Column('nextPaymentAt', sa.Date(), nullable=True),
    sa.Column('startAt', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_studentId'), ['studentId'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_studentId'))

    op.drop_table('enrollments')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_studentCode'))

    op.drop_table('students')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
