"""add schedule tables

Revision ID: c0d436e614a1
Revises: a4b9c9a82439
Create Date: 2026-06-19 01:40:03.455337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d436e614a1'
down_revision: Union[str, Sequence[str], None] = 'a4b9c9a82439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term_schedule_settings',
    sa.Column('termId', sa.Integer(), nullable=False),
    sa.Column('workingDays', sa.JSON(), nullable=False),
    sa.Column('dayStart', sa.Time(), nullable=False),
    sa.Column('dayEnd', sa.Time(), nullable=False),
    sa.Column('defaultDuration', sa.SmallInteger(), nullable=False),
    sa.Column('defaultPerDay', sa.SmallInteger(), nullable=False),
    sa.Column('breakMin', sa.SmallInteger(), nullable=False),
    sa.Column('teacherRules', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], name=op.f('fk_term_schedule_settings_createdBy_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['termId'], ['terms.id'], name=op.f('fk_term_schedule_settings_termId_terms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.id'], name=op.f('fk_term_schedule_settings_updatedBy_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_term_schedule_settings')),
    sa.UniqueConstraint('termId', name='uq_term_schedule_settings_termId')
    )
    with op.batch_alter_table('term_schedule_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_term_schedule_settings_termId'), ['termId'], unique=False)

    op.create_table('schedule_configs',
    sa.Column('classId', sa.Integer(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classId'], ['classes.id'], name=op.f('fk_schedule_configs_classId_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], name=op.f('fk_schedule_configs_createdBy_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.id'], name=op.f('fk_schedule_configs_updatedBy_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_configs')),
    sa.UniqueConstraint('classId', name='uq_schedule_configs_classId')
    )
    with op.batch_alter_table('schedule_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_configs_classId'), ['classId'], unique=False)

    op.create_table('schedule_sessions',
    sa.Column('classLessonId', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('startTime', sa.Time(), nullable=False),
    sa.Column('endTime', sa.Time(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classLessonId'], ['class_lessons.id'], name=op.f('fk_schedule_sessions_classLessonId_class_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], name=op.f('fk_schedule_sessions_createdBy_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.id'], name=op.f('fk_schedule_sessions_updatedBy_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_sessions'))
    )
    with op.batch_alter_table('schedule_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_sessions_classLessonId'), ['classLessonId'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_sessions_classLessonId'))

    op.drop_table('schedule_sessions')
    with op.batch_alter_table('schedule_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_configs_classId'))

    op.drop_table('schedule_configs')
    with op.batch_alter_table('term_schedule_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_term_schedule_settings_termId'))

    op.drop_table('term_schedule_settings')
    # ### end Alembic commands ###
