"""add invites and student profile fields

Revision ID: d8f72b7ed10c
Revises: 9524731a151b
Create Date: 2026-06-03 21:26:19.331266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f72b7ed10c'
down_revision: Union[str, Sequence[str], None] = '9524731a151b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('tckn', sa.String(length=11), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lang', sa.String(length=64), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'cancelled', name='inviteStatus', native_enum=False), server_default='pending', nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invites_tckn'), ['tckn'], unique=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tckn', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('birthDate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('educationLevel', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('contactName', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contactRelation', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('contactPhone', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('contactPhone')
        batch_op.drop_column('contactRelation')
        batch_op.drop_column('contactName')
        batch_op.drop_column('grade')
        batch_op.drop_column('department')
        batch_op.drop_column('school')
        batch_op.drop_column('educationLevel')
        batch_op.drop_column('address')
        batch_op.drop_column('city')
        batch_op.drop_column('gender')
        batch_op.drop_column('birthDate')
        batch_op.drop_column('tckn')

    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invites_tckn'))

    op.drop_table('invites')
    # ### end Alembic commands ###
