"""add day_windows to term_schedule_settings

Revision ID: e382b8da3695
Revises: c0d436e614a1
Create Date: 2026-06-19 18:18:13.558166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e382b8da3695'
down_revision: Union[str, Sequence[str], None] = 'c0d436e614a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term_schedule_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dayWindows', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term_schedule_settings', schema=None) as batch_op:
        batch_op.drop_column('dayWindows')

    # ### end Alembic commands ###
