"""add schedule_rule_templates

Revision ID: e49765c5ecaf
Revises: feff90fea9a7
Create Date: 2026-06-20 02:03:46.548836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49765c5ecaf'
down_revision: Union[str, Sequence[str], None] = 'feff90fea9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_rule_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], name=op.f('fk_schedule_rule_templates_createdBy_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.id'], name=op.f('fk_schedule_rule_templates_updatedBy_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_rule_templates')),
    sa.UniqueConstraint('name', name=op.f('uq_schedule_rule_templates_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_rule_templates')
    # ### end Alembic commands ###
