"""add locked to schedule_sessions

Revision ID: feff90fea9a7
Revises: e382b8da3695
Create Date: 2026-06-19 19:35:20.055277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feff90fea9a7'
down_revision: Union[str, Sequence[str], None] = 'e382b8da3695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_sessions', schema=None) as batch_op:
        batch_op.drop_column('locked')

    # ### end Alembic commands ###
